### PR TITLE
[CARBONDATA-1447] Added the CNCF link in the Website

### PR DESCRIPTION
**Pull request by PallaviSingh1992**

### CODE REVIEW

**Comment by chenliang613** [comment]
@PallaviSingh1992  please create an apache jira issue for this pull request as per "how to contribute guide", thanks.

**Comment by PallaviSingh1992** [comment]
@chenliang613 created the issue: https://issues.apache.org/jira/browse/CARBONDATA-1447

**Comment by chenliang613** [comment]
LGTM

**Comment by sgururajshetty** [comment]
LGTM

**Pull request merged**
